// Two consumers:
//   1. Browser — loaded as <script src="libraries.js">, exposes LIBRARIES global
//   2. Python scraper (scripts/update_models.py) — strips "const LIBRARIES =" wrapper and parses as JSON
// Keys must therefore be quoted (valid JSON). Do not change to unquoted JS shorthand.
const LIBRARIES = [
  { "library": "llama3.2",        "organization": "Meta",                  "origin": "USA",         "source": null,        "multimodal": true },
  { "library": "llama3.1",        "organization": "Meta",                  "origin": "USA",         "source": null },
  { "library": "mistral",         "organization": "Mistral AI",            "origin": "France",      "source": null },
  { "library": "gemma3",          "organization": "Google DeepMind",       "origin": "USA",         "source": "https://ai.google.dev/gemma/docs/integrations/ollama", "multimodal": true },
  { "library": "phi4",            "organization": "Microsoft",             "origin": "USA",         "source": "https://techcommunity.microsoft.com/blog/educatordeveloperblog/welcome-to-the-new-phi-4-models---microsoft-phi-4-mini--phi-4-multimodal/4386037" },
  { "library": "llama3",          "organization": "Meta",                  "origin": "USA",         "source": null },
  { "library": "codellama",       "organization": "Meta",                  "origin": "USA",         "source": null },
  { "library": "mixtral",         "organization": "Mistral AI",            "origin": "France",      "source": null },
  { "library": "phi3",            "organization": "Microsoft",             "origin": "USA",         "source": "https://devblogs.microsoft.com/agent-framework/introducing-new-ollama-connector-for-local-models/" },
  { "library": "llava",           "organization": null,                    "origin": null,          "source": null,        "multimodal": true },
  { "library": "llama2",          "organization": "Meta",                  "origin": "USA",         "source": null },
  { "library": "neural-chat",     "organization": "Intel",                 "origin": "USA",         "source": null },
  { "library": "starling-lm",     "organization": null,                    "origin": null,          "source": null },
  { "library": "orca-mini",       "organization": null,                    "origin": null,          "source": null },
  { "library": "zephyr",          "organization": "HuggingFace",           "origin": "France",      "source": null },
  { "library": "dolphin-mixtral", "organization": null,                    "origin": null,          "source": null },
  { "library": "nous-hermes2",    "organization": "Nous Research",         "origin": "USA",         "source": null },
  { "library": "openhermes",      "organization": null,                    "origin": null,          "source": null },
  { "library": "starcoder2",      "organization": "BigCode / HuggingFace", "origin": "France",      "source": null },
  { "library": "tinyllama",       "organization": "SUTD",                  "origin": "Singapore",   "source": null },
  { "library": "command-r",       "organization": "Cohere",                "origin": "Canada",      "source": null },
  { "library": "granite3-dense",  "organization": "IBM",                   "origin": "USA",         "source": null },
  { "library": "codegemma",       "organization": "Google DeepMind",       "origin": "USA",         "source": null },
  { "library": "moondream",       "organization": null,                    "origin": null,          "source": null,        "multimodal": true },
  { "library": "wizardlm2",       "organization": "Microsoft",             "origin": "USA",         "source": null },
  { "library": "solar",           "organization": "Upstage",               "origin": "South Korea", "source": null },
  { "library": "stablelm2",       "organization": "Stability AI",          "origin": "UK",          "source": null },
  { "library": "mistral-nemo",    "organization": "Mistral AI",            "origin": "France",      "source": null },
  { "library": "llama3.3",        "organization": "Meta",                  "origin": "USA",         "source": null },
  { "library": "gemma2",          "organization": "Google DeepMind",       "origin": "USA",         "source": null },
  { "library": "codestral",       "organization": "Mistral AI",            "origin": "France",      "source": null },
  { "library": "mistral-small",   "organization": "Mistral AI",            "origin": "France",      "source": null },
  { "library": "devstral",        "organization": "Mistral AI",            "origin": "France",      "source": null },
  { "library": "mistral-small3.1", "organization": "Mistral AI",          "origin": "France",      "source": null,        "multimodal": true },
  { "library": "mistral-small3.2", "organization": "Mistral AI",          "origin": "France",      "source": null,        "multimodal": true },
  { "library": "mistral-large",  "organization": "Mistral AI",            "origin": "France",      "source": null },
  { "library": "mathstral",      "organization": "Mistral AI",            "origin": "France",      "source": null },
  { "library": "ministral-3",    "organization": "Mistral AI",            "origin": "France",      "source": null,        "multimodal": true },
];
