const LIBRARIES = [
  { library: "llama3.2",       organization: "Meta",                  origin: "USA"         },
  { library: "llama3.1",       organization: "Meta",                  origin: "USA"         },
  { library: "mistral",        organization: "Mistral AI",            origin: "France"      },
  { library: "gemma3",         organization: "Google DeepMind",       origin: "USA"         },
  { library: "phi4",           organization: "Microsoft",             origin: "USA"         },
  { library: "llama3",         organization: "Meta",                  origin: "USA"         },
  { library: "codellama",      organization: "Meta",                  origin: "USA"         },
  { library: "mixtral",        organization: "Mistral AI",            origin: "France"      },
  { library: "phi3",           organization: "Microsoft",             origin: "USA"         },
  { library: "llava",          organization: null,                    origin: null          },
  { library: "llama2",         organization: "Meta",                  origin: "USA"         },
  { library: "neural-chat",    organization: "Intel",                 origin: "USA"         },
  { library: "starling-lm",    organization: null,                    origin: null          },
  { library: "orca-mini",      organization: null,                    origin: null          },
  { library: "zephyr",         organization: "HuggingFace",           origin: "France"      },
  { library: "dolphin-mixtral",organization: null,                    origin: null          },
  { library: "nous-hermes2",   organization: "Nous Research",         origin: "USA"         },
  { library: "openhermes",     organization: null,                    origin: null          },
  { library: "starcoder2",     organization: "BigCode / HuggingFace", origin: "France"      },
  { library: "tinyllama",      organization: "SUTD",                  origin: "Singapore"   },
  { library: "command-r",      organization: "Cohere",                origin: "Canada"      },
  { library: "granite3-dense", organization: "IBM",                   origin: "USA"         },
  { library: "codegemma",      organization: "Google DeepMind",       origin: "USA"         },
  { library: "moondream",      organization: null,                    origin: null          },
  { library: "wizardlm2",      organization: "Microsoft",             origin: "USA"         },
  { library: "solar",          organization: "Upstage",               origin: "South Korea" },
  { library: "stablelm2",      organization: "Stability AI",          origin: "UK"          },
  { library: "mistral-nemo",   organization: "Mistral AI",            origin: "France"      },
  { library: "llama3.3",       organization: "Meta",                  origin: "USA"         },
  { library: "gemma2",         organization: "Google DeepMind",       origin: "USA"         },
  { library: "codestral",      organization: "Mistral AI",            origin: "France"      },
  { library: "mistral-small",  organization: "Mistral AI",            origin: "France"      },
  { library: "devstral",       organization: "Mistral AI",            origin: "France"      },
];
