const QUANT_INFO = {
  // IQ — importance-matrix quantization; smarter bit allocation than plain Q methods
  'IQ1_S':    { speed: 'Fastest',   quality: 'Severe loss',    summary: 'Use only when the model would not otherwise fit in VRAM at all' },
  'IQ1_M':    { speed: 'Fastest',   quality: 'Severe loss',    summary: 'Marginally more room than IQ1_S; still only for when the model barely fits' },
  'IQ2_XXS':  { speed: 'Very fast', quality: 'Heavy loss',     summary: 'Use when VRAM is very tight; smarter compression than Q2_K at similar file size' },
  'IQ2_XS':   { speed: 'Very fast', quality: 'Heavy loss',     summary: 'A step up from IQ2_XXS when you have slightly more VRAM to spare' },
  'IQ2_S':    { speed: 'Very fast', quality: 'Noticeable loss', summary: 'Approaches Q3 results while staying at 2-bit file size; good when VRAM is scarce' },
  'IQ2_M':    { speed: 'Very fast', quality: 'Noticeable loss', summary: 'Best 2-bit option; approaches Q3_K_S results in a significantly smaller file' },
  'IQ3_XXS':  { speed: 'Fast',      quality: 'Noticeable loss', summary: 'Use when 3-bit size is the constraint but plain Q3_K_S feels wasteful' },
  'IQ3_XS':   { speed: 'Fast',      quality: 'Moderate loss',  summary: 'Solid middle ground in the IQ3 family; more efficient than Q3_K_M at similar size' },
  'IQ3_S':    { speed: 'Fast',      quality: 'Moderate loss',  summary: 'Consistently outperforms plain Q3 variants; prefer over Q3_K_S or Q3_K_M when available' },
  'IQ3_M':    { speed: 'Fast',      quality: 'Moderate loss',  summary: 'Best 3-bit option overall; approaches Q4_K_S results while staying at 3-bit file size' },
  'IQ4_XS':   { speed: 'Fast',      quality: 'Low loss',       summary: 'Very popular; near Q4_K_M results in a smaller file — often the smart 4-bit pick' },
  'IQ4_NL':   { speed: 'Fast',      quality: 'Low loss',       summary: 'Non-linear variant of IQ4; marginal edge over IQ4_XS — use when available' },
  // Q — standard block quantization
  'Q2_K':     { speed: 'Fastest',   quality: 'Severe loss',    summary: 'Use only when the model would not otherwise fit in VRAM' },
  'Q3_K_S':   { speed: 'Very fast', quality: 'Heavy loss',     summary: 'Use when VRAM is tight and fitting the model is the priority' },
  'Q3_K_M':   { speed: 'Very fast', quality: 'Noticeable loss', summary: 'Modest VRAM increase over Q3_K_S; reasonable 3-bit compromise' },
  'Q3_K_L':   { speed: 'Very fast', quality: 'Noticeable loss', summary: 'Best standard 3-bit option; prefer over Q3_K_S/M when you can afford the extra size' },
  'Q4_0':     { speed: 'Fast',      quality: 'Moderate loss',  summary: 'Older 4-bit method; Q4_K_M gives better results for the same VRAM' },
  'Q4_1':     { speed: 'Fast',      quality: 'Moderate loss',  summary: 'Marginal step up from Q4_0; Q4_K_M is almost always the better pick' },
  'Q4_K_S':   { speed: 'Fast',      quality: 'Moderate loss',  summary: 'Good when VRAM is slightly tight; a little smaller than Q4_K_M' },
  'Q4_K_M':   { speed: 'Fast',      quality: 'Low loss',       summary: 'The most popular choice; best size-to-results ratio in the 4-bit family' },
  'Q5_0':     { speed: 'Moderate',  quality: 'Low loss',       summary: 'Older 5-bit method; Q5_K_M is a better use of the same VRAM' },
  'Q5_1':     { speed: 'Moderate',  quality: 'Low loss',       summary: 'Marginal step up from Q5_0; Q5_K_M is almost always the better pick' },
  'Q5_K_S':   { speed: 'Moderate',  quality: 'Low loss',       summary: 'Use when you want 5-bit precision but need to save a little VRAM over Q5_K_M' },
  'Q5_K_M':   { speed: 'Moderate',  quality: 'Minimal loss',   summary: 'Near-original results; use when VRAM allows and you want to minimise compression' },
  'Q6_K':     { speed: 'Slower',    quality: 'Minimal loss',   summary: 'Barely distinguishable from full precision; use when VRAM is ample and compression must be minimal' },
  'Q8_0':     { speed: 'Slow',      quality: 'Near-lossless',  summary: 'Effectively lossless; use for benchmarking or to rule out quantization as a variable' },
  // Full precision
  'F16':      { speed: 'Slowest',   quality: 'Lossless',       summary: 'Full 16-bit precision baseline; use when VRAM is not a constraint' },
  'FP16':     { speed: 'Slowest',   quality: 'Lossless',       summary: 'Full 16-bit precision baseline; use when VRAM is not a constraint' },
  'BF16':     { speed: 'Slowest',   quality: 'Lossless',       summary: 'Brain float 16-bit; same precision as F16 but better suited to modern hardware — prefer over F16 when available' },
  'F32':      { speed: 'Slowest',   quality: 'Lossless',       summary: 'Full 32-bit float; maximum precision but rarely needed or beneficial for inference' },
};
